version = 1
SPDX-PackageName = "docs"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/docs"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "CODEOWNERS",
    "Dockerfile",
    "Makefile",
    "mkdocs.yml",
    "REUSE.toml",
    "hack/**",
    "package-lock.json",
    "package.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**",
    "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
